apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ko-pipeline
  namespace: ko
spec:
  workspaces:
    - name: shared-workspaces
    - name: kubeDir
      optional: true
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspaces
      params:
        - name: url
          value: https://github.com/tektoncd/hub
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"

    - name: ko-00-config
      taskRef:
        name: ko
      workspaces:
        - name: source
          workspace: shared-workspaces
      params:
        - name: imageRegistry
          value: quay.io/skopeotest
        - name: contextDir
          value: "api/config"
        - name: script
          value: ko resolve -f 00-config > 00-config.yaml
        - name: applyName
          value: 00-config.yaml
      runAfter:
        - git-clone

    - name: ko-config
      taskRef:
        name: ko
      workspaces:
        - name: source
          workspace: shared-workspaces
      params:
        - name: imageRegistry
          value: quay.io/skopeotest
        - name: contextDir
          value: "api"
        - name: script
          value: |
            rm -rf config/00-config.yaml
            ko resolve --platform=all --preserve-import-paths -f config > config.yaml
        - name: applyName
          value: config.yaml
      runAfter:
        - ko-00-config
