apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ko-pipeline
  namespace: ko
spec:
  workspaces:
    - name: shared-workspaces
    - name: kubeDir
      optional: true
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspaces
      params:
        - name: url
          value: https://github.com/tektoncd/hub
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"

    - name: ko-00-config
      taskRef:
        name: ko
      workspaces:
        - name: source
          workspace: shared-workspaces
      params:
        - name: imageRegistry
          value: quay.io/skopeotest
        - name: contextDir
          value: "api/config"
        - name: script
          value: ko resolve -f 00-config > 00-config.yaml
        - name: applyName
          value: 00-config.yaml
      runAfter:
        - git-clone

    - name: ko-config
      taskRef:
        name: ko
      workspaces:
        - name: source
          workspace: shared-workspaces
      params:
        - name: imageRegistry
          value: quay.io/skopeotest
        - name: contextDir
          value: "api"
        - name: script
          value: |
            rm -rf config/00-config.yaml
            cat <<EOF > .ko.yaml
            baseImageOverrides:
              github.com/tektoncd/hub/api/cmd/api: quay.io/tekton-hub/go-base:latest
            EOF
            cat .ko.yaml
            ko resolve -f config > config.yaml
        - name: applyName
          value: config.yaml
      runAfter:
        - ko-00-config
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ko-pipeline-run
  namespace: ko
spec:
  pipelineRef:
    name: ko-pipeline
  serviceAccountName: secret-service-account
  workspaces:
    - name: shared-workspaces
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 500Mi
