apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ko-pipeline-run
  namespace: ko
spec:
  pipelineRef:
    name: ko-pipeline
  serviceAccountName: secret-service-account
  workspaces:
    - name: shared-workspaces
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 500Mi
    # - name: temp
    #   volumeClaimTemplate:
    #     spec:
    #       accessModes:
    #         - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
    #       resources:
    #         requests:
    #           storage: 10Mi
